sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7

before_script:
  - composer self-update
  - composer install --prefer-source
  - mkdir -p tests/build/logs

script:
  - vendor/bin/phpunit -c ./phpunit.xml
  - ./vendor/bin/phpcs --standard=PSR2 ./src/

notifications:
  irc: "irc.freenode.org#zftalk.modules"
  email: false
